- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest:mysql
  tasks:
  - name: Add a new user
    user:
      name: ags
      shell: /bin/bash
  - name: Deploy SSH Key
    authorized_key:
      user: ags
      key: "{{ lookup('file', '/home/ags/.ssh/id_rsa.pub') }}"
      state: present
  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/ags"
      content: "ags  ALL=(ALL)  NOPASSWD: ALL"
  - import_role:
      name: confluent.common
  - import_role:
      name: confluent.kerberos
    when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms and kerberos_configure|bool"
  - import_role:
      name: confluent.ssl
    when: kafka_broker_listeners | ssl_required

- name: Mysql Provisioning
  hosts: mysql
  tags:
    - mysql
  tasks:
    - name: Install mysql packages
      package:
        name:
          - mysql-client
          - mysql-common
          - mysql-server
        state: present

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  gather_facts: no
  tags:
    - schema_registry
  tasks:
  - import_role:
      name: confluent.schema_registry

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: no
  tags:
    - ksql
  tasks:
  - import_role:
      name: confluent.ksql

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: no
  tags:
    - kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: no
  tags:
    - control_center
  tasks:
  - import_role:
      name: confluent.control_center
